###
# 교보리얼코 전자구매시스템  설정 
#    
###
  
spring:
  application:
    name: epsproto-ui
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    database: SQL_SERVER
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
      #naming.implicit-strategy
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  datasource:
    platform: mssql
#    url: jdbc:sqlserver://localhost:1433;instance=DESKTOP-NAETGOS\SQLEXPRESS;databaseName=KREPS
#    username: sa
#    password: qwer1234
    url: jdbc:sqlserver://152.149.199.204:1433;databaseName=KREPS;
    username: kpms2
    password: kpms@Pass
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: D:/realco-kreps/kreps-files/temp
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    #check-template-location: true
    mode: HTML5
    suffix: .html     

server:
  port: 8282
  servlet:
    context-path: /
    session:
      tracking-modes: cookie
  #tomcat:
  #  basedir: tomcat
  #  accesslog:
  #    enabled: true
  #    suffix: .log
  #    prefix: acess_log
  #    file-date-format: .yyyy-MM-dd
  #    directory: logs
  #    pattern: common

#logging:
#  file:
#    name: /tomcat/kreps-vendor.log
#  level:
#    org.apache.tomcat: DEBUG
#    org.apache.catalina: DEBUG
#  pattern:
#    dateformat: yyyy-MM-dd HH:mm:ss
#    file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p}
#      ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
#    level: '%5p'
#    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz    